[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip nRF52833_xxAA --catch-hardfault --catch-reset"
rustflags = ["-C", "linker=rust-lld", "-C", "link-arg=-Tlink.x"]
