[package]
name = "example_04_asm"
authors = ["Neil Pate"]
edition = "2021"
version = "0.1.0"

[dependencies]
# Zero external dependencies - all functionality implemented in ARM assembly

[[bin]]
name = "main"
path = "src/main.rs"
test = false
bench = false
